//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToLuaGameFramework_LuaConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToLuaGameFramework.LuaConfig), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("UseLuaBundle", get_UseLuaBundle, null);
		L.RegVar("UseResBundle", get_UseResBundle, null);
		L.RegVar("LuaDevPath", get_LuaDevPath, null);
		L.RegVar("OutputPath_Android", get_OutputPath_Android, null);
		L.RegVar("OutputPath_IOS", get_OutputPath_IOS, null);
		L.RegVar("OutputPath_PC", get_OutputPath_PC, null);
		L.RegVar("RemoteUrl", get_RemoteUrl, null);
		L.RegVar("ExportLuaPaths", get_ExportLuaPaths, set_ExportLuaPaths);
		L.RegVar("ExportRes_For_Startup", get_ExportRes_For_Startup, set_ExportRes_For_Startup);
		L.RegVar("ExportRes_For_Delay", get_ExportRes_For_Delay, set_ExportRes_For_Delay);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseLuaBundle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, ToLuaGameFramework.LuaConfig.UseLuaBundle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseResBundle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, ToLuaGameFramework.LuaConfig.UseResBundle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaDevPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.LuaDevPath);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_Android(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_Android);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_IOS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_IOS);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_PC(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_PC);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RemoteUrl(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.RemoteUrl);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportLuaPaths(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ToLuaGameFramework.LuaConfig.ExportLuaPaths);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportRes_For_Startup(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, ToLuaGameFramework.LuaConfig.ExportRes_For_Startup);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportRes_For_Delay(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, ToLuaGameFramework.LuaConfig.ExportRes_For_Delay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportLuaPaths(IntPtr L)
	{
		try
		{
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			ToLuaGameFramework.LuaConfig.ExportLuaPaths = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportRes_For_Startup(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<string,string> arg0 = (System.Collections.Generic.Dictionary<string,string>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,string>));
			ToLuaGameFramework.LuaConfig.ExportRes_For_Startup = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportRes_For_Delay(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<string,string> arg0 = (System.Collections.Generic.Dictionary<string,string>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,string>));
			ToLuaGameFramework.LuaConfig.ExportRes_For_Delay = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

